### ISSUE TITLE
Tracking issue: Create a framework for a c-extension

### ISSUE THREAD

**Issue by mattip** [Quansight/numpy-threading-extensions#2]
Create a c-extension module that follows best practices

- [x]  supports testing and CI on all the CPU architectures the code supports
- [x] supports documentation generation via Sphinx
- [x] will be uploaded to PyPI and available via conda-forge

**Comment by mattip** [comment]
Progress made: I have created a project template with cookie cutter, renamed the default branch to `main`, and pushed the result.

**Comment by mattip** [comment]
Closing
